export type Project = {
  // Identity
  slug: string;                    // URL: /projects/{slug}
  index: string;                   // "01", "02" ...

  // Short fields (used on homepage card)
  category: string;                // "AI / PRODUCT"
  title: string;
  subtitle: string;
  shortDescription: string;        // 1 sentence for the card
  tags: string[];
  image: string;
  year: string;
  liveUrl?: string;
  repoUrl?: string;
  featured?: boolean;

  // Long-form fields (used on case study page)
  fullDescription: string[];       // 4-6 sentences, split into 1-2 paragraphs
  keyFeatures: string[];           // 4-6 bullet points
  howItWorks: {
    input: string;
    process: string;
    output: string;
  };
  techStack: {
    label: string;                 // "Frontend" / "Backend" / "AI" etc.
    items: string[];
  }[];
  note?: string;                   // optional line for experimental projects
};

export const projects: Project[] = [
  // ============================================================
  // 01 - StudyAI (featured, fully written)
  // ============================================================
  {
    slug: "studyai",
    index: "01",
    category: "AI / PRODUCT",
    title: "StudyAI",
    subtitle: "AI Academic Productivity Platform",
    shortDescription:
      "An AI-powered platform that turns messy assignment input into structured study plans with summaries, task breakdowns, and time estimates.",
    tags: ["Next.js", "TypeScript", "Tailwind", "AI", "APIs"],
    image: "/images/studyai.png",
    year: "2025",
    liveUrl: "https://example.com",
    repoUrl: "https://github.com/yourhandle/studyai",
    featured: true,

    fullDescription: [
      "StudyAI is a productivity platform for students who juggle multiple courses, deadlines, and unclear syllabi. Users paste in a raw assignment or syllabus and the system returns a clear breakdown: the deliverables, suggested sub-tasks, time estimates, and a compact summary of what the assignment is actually asking for.",
      "The product is built around a single idea: most academic overwhelm is not a workload problem but a parsing problem. Turning a dense paragraph of instructions into a structured plan removes the friction that usually sits between a student and their first productive hour. StudyAI handles that parsing in one step, using AI to extract intent, identify milestones, and suggest a realistic schedule around the user's available time.",
    ],
    keyFeatures: [
      "Paste any assignment or syllabus text and get an instant, structured breakdown",
      "AI-generated summary surfaces what the assignment is actually asking for",
      "Automatic task decomposition with suggested time estimates per sub-task",
      "Schedule view that fits tasks into the user's available hours across the week",
      "Real-time follow-up: ask clarifying questions about the assignment and get grounded answers",
      "Persistent plans that can be revisited, edited, and marked complete",
    ],
    howItWorks: {
      input:
        "The user pastes an assignment prompt, syllabus excerpt, or task description into a single input field. No formatting or tagging required.",
      process:
        "The text is sent to a language model through a structured prompt that extracts deliverables, identifies implicit sub-tasks, estimates time per task, and generates a short summary. The output is validated against a schema before being returned to the client.",
      output:
        "The user receives a structured plan on screen: summary at the top, ordered sub-tasks with time estimates, and a weekly schedule view. Every item is editable and saved to the user's workspace.",
    },
    techStack: [
      { label: "Frontend", items: ["Next.js", "TypeScript", "Tailwind CSS"] },
      { label: "Backend", items: ["Next.js API Routes", "PostgreSQL"] },
      { label: "AI", items: ["OpenAI API", "Structured output with Zod"] },
      { label: "Infra", items: ["Vercel", "Supabase"] },
    ],
  },

  // ============================================================
  // 02 - FitCoach AI
  // ============================================================
  {
    slug: "fitcoach-ai",
    index: "02",
    category: "MOBILE AI",
    title: "FitCoach AI",
    subtitle: "AI Fitness and Nutrition App",
    shortDescription:
      "A mobile-first app that delivers adaptive workout and nutrition plans generated by AI and refined by user progress.",
    tags: ["React Native", "OpenAI", "Mobile", "Context API"],
    image: "/images/fitcoach.png",
    year: "2025",
    liveUrl: "https://example.com",
    repoUrl: "https://github.com/yourhandle/fitcoach-ai",

    fullDescription: [
      "FitCoach AI is a mobile application that generates personalized workout and nutrition plans based on user goals, current fitness level, and available equipment. The app is designed to replace the generic template plans that most fitness apps ship with, instead producing a coaching experience that adapts over time.",
      "Rather than asking users to pick from pre-built routines, the app treats each user's inputs as a starting point and uses AI to compose a plan that fits their reality. As users log workouts and meals, the plan adjusts the following week based on what actually happened, not what was originally prescribed.",
    ],
    keyFeatures: [
      "Personalized workout plans generated from user goals, experience, and equipment",
      "Nutrition guidance calibrated to weight and performance goals",
      "Adaptive weekly adjustments based on completed sessions and user feedback",
      "Clean tracking interface for logging exercises, sets, and meals",
      "Responsive mobile-first UI with offline-friendly state handling",
    ],
    howItWorks: {
      input:
        "During onboarding, the user provides goals, current fitness level, available equipment, dietary preferences, and time commitment.",
      process:
        "The inputs are composed into a structured prompt and sent to the AI, which returns a weekly plan covering workouts and nutrition. As the user logs completions, those logs are fed back into the system to inform the next week's plan.",
      output:
        "A daily plan on the home screen showing the workout, meals, and progress markers. Users can edit, skip, or swap items, and the app records those changes for future adjustments.",
    },
    techStack: [
      { label: "Mobile", items: ["React Native", "Expo", "Context API"] },
      { label: "AI", items: ["OpenAI API"] },
      { label: "Backend", items: ["Node.js", "REST APIs"] },
    ],
  },

  // ============================================================
  // 03 - AbsoluteJS Platform
  // ============================================================
  {
    slug: "absolutejs",
    index: "03",
    category: "TEAM / PLATFORM",
    title: "AbsoluteJS Platform",
    subtitle: "Industry-Sponsored Development Platform",
    shortDescription:
      "A performance-focused web development platform built with a collaborative team, focused on scalability and type safety.",
    tags: ["React", "TypeScript", "PostgreSQL", "Agile"],
    image: "/images/absolutejs.png",
    year: "2024",
    liveUrl: "https://example.com",
    repoUrl: "https://github.com/yourhandle/absolutejs",

    fullDescription: [
      "AbsoluteJS is a web development platform built in collaboration with an industry sponsor, focused on delivering a type-safe, scalable foundation for modern applications. The platform includes reusable UI components, database integration patterns, and documentation designed for developer adoption.",
      "My contributions centered on the component library and integration workflows. I worked within an agile team, participating in reviews, writing documentation, and refining components so that downstream teams could ship faster without compromising on type safety or performance.",
    ],
    keyFeatures: [
      "Reusable, type-safe UI component library",
      "Integration patterns for PostgreSQL and modern frameworks",
      "Developer-facing documentation and usage examples",
      "Collaborative agile workflow with code review and iteration cycles",
      "Performance-conscious defaults for scaling to real traffic",
    ],
    howItWorks: {
      input:
        "Downstream developers install the library, configure a database connection, and compose their application using the provided components and patterns.",
      process:
        "The platform handles type generation, data fetching, and UI rendering through shared primitives. Updates are versioned and documented so teams can upgrade predictably.",
      output:
        "A consistent, fast, type-safe foundation that reduces boilerplate and shortens the path from idea to working product.",
    },
    techStack: [
      { label: "Frontend", items: ["React", "TypeScript"] },
      { label: "Backend", items: ["PostgreSQL", "Node.js"] },
      { label: "Workflow", items: ["Agile", "Code Review", "Documentation"] },
    ],
  },

  // ============================================================
  // 04 - Music AI Video Generator
  // ============================================================
  {
    slug: "music-ai",
    index: "04",
    category: "AI / CREATIVE",
    title: "Music AI Video Generator",
    subtitle: "AI Creative Generation Platform",
    shortDescription:
      "An experimental system that generates complete music videos from text input, chaining lyrics, audio, and visual generation.",
    tags: ["Python", "AI", "ML", "Audio", "Image Generation"],
    image: "/images/music-ai.png",
    year: "2024",
    repoUrl: "https://github.com/yourhandle/music-ai",

    fullDescription: [
      "Music AI Video Generator is an experimental system that takes a short text prompt and produces a complete music video, including generated lyrics, a short audio track, and a sequence of visual frames tied to the music. The project explores what end-to-end creative generation looks like when multiple AI models are chained into a single pipeline.",
      "The focus was on orchestration: getting several independent generation steps to hand off cleanly and produce an output that feels coherent rather than stitched together. The result is not a production tool but a working prototype that demonstrates the idea end-to-end.",
    ],
    keyFeatures: [
      "Full pipeline from text prompt to finished music video",
      "AI-generated lyrics tailored to the prompt theme",
      "Short-form audio composition layered with the lyrics",
      "Frame-by-frame visual generation synchronized to the audio",
      "Modular pipeline design so individual stages can be swapped",
    ],
    howItWorks: {
      input:
        "The user provides a short prompt describing the mood, theme, or scene they want in a music video.",
      process:
        "The prompt flows through a chain of generation stages: lyrics first, then audio composition, then visual frame generation conditioned on both the lyrics and the audio. Each stage's output feeds into the next.",
      output:
        "A short music video file combining the generated audio and visuals, ready to preview or download.",
    },
    techStack: [
      { label: "AI / ML", items: ["Python", "Audio generation models", "Image generation models"] },
      { label: "Pipeline", items: ["Custom orchestration layer"] },
    ],
    note:
      "Developed as an experimental project to explore multi-stage generative pipelines, focusing on system design rather than full production deployment.",
  },

  // ============================================================
  // 05 - Job Club
  // ============================================================
  {
    slug: "job-club",
    index: "05",
    category: "WEB / COMMUNITY",
    title: "Job Club",
    subtitle: "Career and Community Platform",
    shortDescription:
      "A web platform that helps students explore career paths, access resources, and connect with a learning community.",
    tags: ["React", "Vercel", "Web"],
    image: "/images/job-club.png",
    year: "2024",
    liveUrl: "https://example.com",
    repoUrl: "https://github.com/yourhandle/job-club",

    fullDescription: [
      "Job Club is a web platform that serves as a starting point for students navigating early career decisions. It collects career paths, resources, and community connections in one place, with a focus on clear navigation and accessible design.",
      "The product prioritizes getting the user to the right next step quickly. Rather than overwhelming visitors with feeds or feeds-of-feeds, the layout is built around explicit paths: pick a direction, see the resources for that direction, and connect with others on the same track.",
    ],
    keyFeatures: [
      "Curated career paths with linked resources",
      "Community directory for connecting with peers",
      "Accessible, keyboard-friendly navigation",
      "Mobile-responsive layout",
      "Clean information architecture optimized for quick scanning",
    ],
    howItWorks: {
      input:
        "The user selects a career direction or browses by topic.",
      process:
        "The platform surfaces the resources and community members tagged to that direction, filtered by the user's context if available.",
      output:
        "A focused list of next steps: articles, tools, people to talk to, and events relevant to that path.",
    },
    techStack: [
      { label: "Frontend", items: ["React", "Tailwind CSS"] },
      { label: "Infra", items: ["Vercel"] },
    ],
  },

  // ============================================================
  // 06 - Watch Showcase
  // ============================================================
  {
    slug: "watch-showcase",
    index: "06",
    category: "FULL-STACK",
    title: "Watch Showcase",
    subtitle: "Full-Stack Web Application",
    shortDescription:
      "A Django-based application for browsing and reviewing luxury watches, with user authentication and relational database design.",
    tags: ["Django", "Python", "PostgreSQL"],
    image: "/images/watches.png",
    year: "2024",
    repoUrl: "https://github.com/yourhandle/watch-showcase",

    fullDescription: [
      "Watch Showcase is a full-stack web application for cataloging, browsing, and reviewing luxury watches. It covers the full stack end to end: user authentication, a relational data model, form handling with validation, and a review system with user-generated content.",
      "The project is deliberately scoped as a foundation: a place where the backend decisions are made carefully and the frontend is built to expose those decisions clearly. It demonstrates the full request-to-response lifecycle of a traditional web application.",
    ],
    keyFeatures: [
      "User authentication with secure session handling",
      "Catalog of watches with filtering and search",
      "Review system with user-generated content and moderation hooks",
      "Relational data model covering brands, models, reviews, and users",
      "Server-side rendering with Django templates",
    ],
    howItWorks: {
      input:
        "A user signs in, browses the catalog, and optionally submits a review on a specific watch.",
      process:
        "Requests are routed through Django views, data is fetched or written to PostgreSQL, and form input is validated server-side before persisting.",
      output:
        "Rendered HTML pages showing watch details, existing reviews, and the user's own submissions.",
    },
    techStack: [
      { label: "Backend", items: ["Django", "Python", "PostgreSQL"] },
      { label: "Frontend", items: ["Django templates", "CSS"] },
    ],
  },
];

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug);
}